[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "conda_index"
authors = [{name = "Anaconda, Inc. & Contributors", email = "conda@continuum.io"}]
readme = "README.md"
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/conda-incubator/conda-index"
